version: '3.9'

services:
  php-app:
    build:
      context: .
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes: 
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
